# sbatch completion script generated by https://github.com/adaszko/complgen v0.10.1-0-g9158856501

function _sbatch_cmd_0
    set 1 $argv[1]
    __fish_complete_directories "$1"
end

function _sbatch_cmd_1
    set 1 $argv[1]
    __fish_complete_path "$1"
end

function _sbatch_cmd_2
    set 1 $argv[1]
    __fish_complete_command
end

function _sbatch_cmd_3
    set 1 $argv[1]
    sacctmgr show account -nP format=account
end

function _sbatch_cmd_4
    set 1 $argv[1]
    squeue --me -ho '%A'
end

function _sbatch_cmd_5
    set 1 $argv[1]
    sinfo -ho '%G' | sed 's/([^)]*)//g' | tr ':' '\n' | grep -v '^[0-9]' | sort -u
end

function _sbatch_cmd_6
    set 1 $argv[1]
    scontrol show lic
end

function _sbatch_cmd_7
    set 1 $argv[1]
    sacctmgr show cluster -nP format=clusters
end

function _sbatch_cmd_8
    set 1 $argv[1]
    sacctmgr show user -nP format=user
end

function _sbatch_cmd_9
    set 1 $argv[1]
    sinfo -ho '%P'
end

function _sbatch_cmd_10
    set 1 $argv[1]
    sacctmgr show qos -nP format=name
end

function _sbatch_cmd_11
    set 1 $argv[1]
    sinfo -ho %f
end

function _sbatch_cmd_12
    set 1 $argv[1]
    sacctmgr show reservation -nP format=name
end

function _sbatch_cmd_13
    set 1 $argv[1]
    sinfo -ho %n
end

function _sbatch_subword_49
    set --global subword_literals ","
    set --global subword_descrs
    set --global subword_descr_literal_ids 
    set --global subword_descr_ids 
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[2] "1"
    set --global subword_literal_transitions_tos[2] "1"
    set --global subword_command_transitions
    set --global subword_command_transitions[1] "6,2"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 2
    set --global subword_literal_inputs_level_1 "1"
    set --global subword_command_froms_level_0 1
    set --global subword_commands_level_0 "6"
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_50
    set --global subword_literals "seconds" "minutes" "+count" "weeks" "hours" "days" "now"
    set --global subword_descrs
    set --global subword_descr_literal_ids 
    set --global subword_descr_ids 
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "7"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[2] "3"
    set --global subword_literal_transitions_tos[2] "3"
    set --global subword_literal_transitions_inputs[3] "1 2 4 5 6"
    set --global subword_literal_transitions_tos[3] "4 4 4 4 4"
    set --global subword_command_transitions
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 1 2 3
    set --global subword_literal_inputs_level_1 "7" "3" "1 2 4 5 6"
    set --global subword_command_froms_level_0 
    set --global subword_commands_level_0 
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_18
    set --global subword_literals "--dependency=" "afternotok" "aftercorr" "afterany" "afterok" "after" ":" ","
    set --global subword_descrs
    set --global subword_descrs[1] "defer job until condition on jobid is satisfied"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[2] "2 3 4 5 6"
    set --global subword_literal_transitions_tos[2] "3 3 3 3 3"
    set --global subword_literal_transitions_inputs[3] "7"
    set --global subword_literal_transitions_tos[3] "4"
    set --global subword_literal_transitions_inputs[5] "7 8"
    set --global subword_literal_transitions_tos[5] "4 2"
    set --global subword_command_transitions
    set --global subword_command_transitions[4] "4,5"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1 2 3 5
    set --global subword_literal_inputs_level_0 "1" "2 3 4 5 6" "7" "7 8"
    set --global subword_command_froms_level_0 4
    set --global subword_commands_level_0 "4"
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_shape_3
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_star_transitions_from 2
    set --global subword_star_transitions_to 3
    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 1
    set --global subword_literal_inputs_level_1 "1"
    set --global subword_command_froms_level_0 
    set --global subword_commands_level_0 
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_39
    set --global subword_literals "--mem="
    set --global subword_descrs
    set --global subword_descrs[1] "minimum amount of real memory"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_3 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_46
    set --global subword_literals "--cpus-per-gpu="
    set --global subword_descrs
    set --global subword_descrs[1] "number of CPUs required per allocated GPU"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_3 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_40
    set --global subword_literals "--mem-per-cpu="
    set --global subword_descrs
    set --global subword_descrs[1] "maximum amount of real memory per allocated cpu required by the job. --mem >= --mem-per-cpu if --mem is specified."
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_3 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_41
    set --global subword_literals "--mem-per-gpu="
    set --global subword_descrs
    set --global subword_descrs[1] "real memory required per allocated GPU"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_3 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_43
    set --global subword_literals "--tmp="
    set --global subword_descrs
    set --global subword_descrs[1] "minimum amount of temporary disk"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_3 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_42
    set --global subword_literals "--reservation="
    set --global subword_descrs
    set --global subword_descrs[1] "allocate resources from named reservation"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "12,3"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 1
    set --global subword_literal_inputs_level_1 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "12"
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_4
    set --global subword_literals "--export=" ",ENVVAR" "NONE" "NIL" "ALL"
    set --global subword_descrs
    set --global subword_descrs[1] "specify environment variables to export"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[2] "3 4 5"
    set --global subword_literal_transitions_tos[2] "4 4 3"
    set --global subword_literal_transitions_inputs[3] "2"
    set --global subword_literal_transitions_tos[3] "4"
    set --global subword_command_transitions
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1 2 3
    set --global subword_literal_inputs_level_0 "1" "3 4 5" "2"
    set --global subword_command_froms_level_0 
    set --global subword_commands_level_0 
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_34
    set --global subword_literals "--qos="
    set --global subword_descrs
    set --global subword_descrs[1] "quality of service"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "10,3"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1
    set --global subword_literal_inputs_level_0 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "10"
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_20
    set --global subword_literals "--gres="
    set --global subword_descrs
    set --global subword_descrs[1] "required generic resources"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "5,3"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1
    set --global subword_literal_inputs_level_0 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "5"
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_51
    set --global subword_literals "HH:MM" ":SS"
    set --global subword_descrs
    set --global subword_descr_literal_ids 
    set --global subword_descr_ids 
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[2] "2"
    set --global subword_literal_transitions_tos[2] "3"
    set --global subword_command_transitions
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 1 2
    set --global subword_literal_inputs_level_1 "1" "2"
    set --global subword_command_froms_level_0 
    set --global subword_commands_level_0 
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_shape_9
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_star_transitions_from 2
    set --global subword_star_transitions_to 3
    set --global subword_literal_froms_level_0 1
    set --global subword_literal_inputs_level_0 "1"
    set --global subword_command_froms_level_0 
    set --global subword_commands_level_0 
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_1
    set --global subword_literals "--array="
    set --global subword_descrs
    set --global subword_descrs[1] "job array index values"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_9 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_29
    set --global subword_literals "--ntasks-per-node="
    set --global subword_descrs
    set --global subword_descrs[1] "number of tasks to invoke on each node"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_9 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_30
    set --global subword_literals "--nodes="
    set --global subword_descrs
    set --global subword_descrs[1] "number of nodes on which to run (N = min[-max])"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_9 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_14
    set --global subword_literals "--cpus-per-task="
    set --global subword_descrs
    set --global subword_descrs[1] "number of cpus required per task"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_9 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_47
    set --global subword_literals "--gpus="
    set --global subword_descrs
    set --global subword_descrs[1] "count of GPUs required for the job"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_9 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_15
    set --global subword_literals "--comment="
    set --global subword_descrs
    set --global subword_descrs[1] "arbitrary comment"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_9 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_17
    set --global subword_literals "--container-id="
    set --global subword_descrs
    set --global subword_descrs[1] "OCI container ID"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_9 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_8
    set --global subword_literals "--wait="
    set --global subword_descrs
    set --global subword_descrs[1] "wait for completion of submitted job"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_9 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_32
    set --global subword_literals "--priority="
    set --global subword_descrs
    set --global subword_descrs[1] "set the priority of the job to value"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_9 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_27
    set --global subword_literals "--ntasks="
    set --global subword_descrs
    set --global subword_descrs[1] "number of tasks to run"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_9 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_12
    set --global subword_literals "--account="
    set --global subword_descrs
    set --global subword_descrs[1] "charge job to specified account"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "3,3"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1
    set --global subword_literal_inputs_level_0 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "3"
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_23
    set --global subword_literals "--distribution=" "arbitrary" "cyclic" "plane" "block"
    set --global subword_descrs
    set --global subword_descrs[1] "distribution method for processes to nodes"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[2] "2 3 4 5"
    set --global subword_literal_transitions_tos[2] "3 3 3 3"
    set --global subword_command_transitions
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1 2
    set --global subword_literal_inputs_level_0 "1" "2 3 4 5"
    set --global subword_command_froms_level_0 
    set --global subword_commands_level_0 
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_25
    set --global subword_literals "TIME_LIMIT_90" "TIME_LIMIT_80" "TIME_LIMIT_50" "--mail-type=" "ARRAY_TASKS" "TIME_LIMIT" "STAGE_OUT" "REQUEUE" "BEGIN" "NONE" "FAIL" "END" "ALL"
    set --global subword_descrs
    set --global subword_descrs[1] "notify on state change: BEGIN, END, FAIL or ALL"
    set --global subword_descr_literal_ids 4
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "4"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[2] "1 2 3 5 6 7 8 9 10 11 12 13"
    set --global subword_literal_transitions_tos[2] "3 3 3 3 3 3 3 3 3 3 3 3"
    set --global subword_command_transitions
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1 2
    set --global subword_literal_inputs_level_0 "4" "1 2 3 5 6 7 8 9 10 11 12 13"
    set --global subword_command_froms_level_0 
    set --global subword_commands_level_0 
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_53
    set --global subword_literals "afternotok" "aftercorr" "afterany" "afterok" "after" ":" ","
    set --global subword_descrs
    set --global subword_descr_literal_ids 
    set --global subword_descr_ids 
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1 2 3 4 5"
    set --global subword_literal_transitions_tos[1] "2 2 2 2 2"
    set --global subword_literal_transitions_inputs[2] "6"
    set --global subword_literal_transitions_tos[2] "3"
    set --global subword_literal_transitions_inputs[4] "6 7"
    set --global subword_literal_transitions_tos[4] "3 1"
    set --global subword_command_transitions
    set --global subword_command_transitions[3] "4,4"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 1 2 4
    set --global subword_literal_inputs_level_1 "1 2 3 4 5" "6" "6 7"
    set --global subword_command_froms_level_0 3
    set --global subword_commands_level_0 "4"
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_35
    set --global subword_literals "YYYY-MM-DD" "seconds" "minutes" "--time=" "THH:MM" "+count" "weeks" "hours" "HH:MM" "days" "now" ":SS"
    set --global subword_descrs
    set --global subword_descrs[1] "time limit"
    set --global subword_descr_literal_ids 4
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "4"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[2] "1 9 11"
    set --global subword_literal_transitions_tos[2] "5 4 3"
    set --global subword_literal_transitions_inputs[3] "6"
    set --global subword_literal_transitions_tos[3] "6"
    set --global subword_literal_transitions_inputs[4] "12"
    set --global subword_literal_transitions_tos[4] "7"
    set --global subword_literal_transitions_inputs[5] "5"
    set --global subword_literal_transitions_tos[5] "4"
    set --global subword_literal_transitions_inputs[6] "2 3 7 8 10"
    set --global subword_literal_transitions_tos[6] "7 7 7 7 7"
    set --global subword_command_transitions
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1 2 3 4 5 6
    set --global subword_literal_inputs_level_0 "4" "1 9 11" "6" "12" "5" "2 3 7 8 10"
    set --global subword_command_froms_level_0 
    set --global subword_commands_level_0 
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_shape_15
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[2] "2 9 11"
    set --global subword_literal_transitions_tos[2] "5 4 3"
    set --global subword_literal_transitions_inputs[3] "6"
    set --global subword_literal_transitions_tos[3] "6"
    set --global subword_literal_transitions_inputs[4] "12"
    set --global subword_literal_transitions_tos[4] "7"
    set --global subword_literal_transitions_inputs[5] "5"
    set --global subword_literal_transitions_tos[5] "4"
    set --global subword_literal_transitions_inputs[6] "3 4 7 8 10"
    set --global subword_literal_transitions_tos[6] "7 7 7 7 7"
    set --global subword_command_transitions
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1 2 3 4 5 6
    set --global subword_literal_inputs_level_0 "1" "2 9 11" "6" "12" "5" "3 4 7 8 10"
    set --global subword_command_froms_level_0 
    set --global subword_commands_level_0 
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_36
    set --global subword_literals "--time-min=" "YYYY-MM-DD" "seconds" "minutes" "THH:MM" "+count" "weeks" "hours" "HH:MM" "days" "now" ":SS"
    set --global subword_descrs
    set --global subword_descr_literal_ids 
    set --global subword_descr_ids 
    _sbatch_subword_shape_15 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_19
    set --global subword_literals "--deadline=" "YYYY-MM-DD" "seconds" "minutes" "THH:MM" "+count" "weeks" "hours" "HH:MM" "days" "now" ":SS"
    set --global subword_descrs
    set --global subword_descrs[1] "remove the job if no ending possible before this deadline (start > (deadline - time[-min]))"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_15 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_28
    set --global subword_literals "--nice" "="
    set --global subword_descrs
    set --global subword_descrs[1] "decrease scheduling priority by value"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[2] "2"
    set --global subword_literal_transitions_tos[2] "3"
    set --global subword_command_transitions
    set --global subword_star_transitions_from 3
    set --global subword_star_transitions_to 4
    set --global subword_literal_froms_level_0 1 2
    set --global subword_literal_inputs_level_0 "1" "2"
    set --global subword_command_froms_level_0 
    set --global subword_commands_level_0 
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_33
    set --global subword_literals "filesystem" "--profile=" "network" "energy" "task" "none" "all" ","
    set --global subword_descrs
    set --global subword_descrs[1] "enable acct_gather_profile for detailed data value is all or none or any combination of energy, lustre, network or task"
    set --global subword_descr_literal_ids 2
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "2"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[2] "1 3 4 5 6 7"
    set --global subword_literal_transitions_tos[2] "4 4 4 4 3 3"
    set --global subword_literal_transitions_inputs[4] "8"
    set --global subword_literal_transitions_tos[4] "5"
    set --global subword_literal_transitions_inputs[5] "1 3 4 5"
    set --global subword_literal_transitions_tos[5] "4 4 4 4"
    set --global subword_command_transitions
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1 2 4 5
    set --global subword_literal_inputs_level_0 "2" "1 3 4 5 6 7" "8" "1 3 4 5"
    set --global subword_command_froms_level_0 
    set --global subword_commands_level_0 
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_38
    set --global subword_literals "--constraint=" ","
    set --global subword_descrs
    set --global subword_descrs[1] "specify a list of constraints"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[3] "2"
    set --global subword_literal_transitions_tos[3] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "11,3"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1 3
    set --global subword_literal_inputs_level_0 "1" "2"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "11"
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_shape_19
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[3] "2"
    set --global subword_literal_transitions_tos[3] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "13,3"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1 3
    set --global subword_literal_inputs_level_0 "1" "2"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "13"
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_44
    set --global subword_literals "--nodelist=" ","
    set --global subword_descrs
    set --global subword_descrs[1] "request a specific list of hosts"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_19 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_45
    set --global subword_literals "--exclude=" ","
    set --global subword_descrs
    set --global subword_descrs[1] "exclude a specific list of hosts"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_19 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_24
    set --global subword_literals "--job-name="
    set --global subword_descrs
    set --global subword_descrs[1] "name of job"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "1,3"
    set --global subword_star_transitions_from 2
    set --global subword_star_transitions_to 3
    set --global subword_literal_froms_level_0 1
    set --global subword_literal_inputs_level_0 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "1"
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_52
    set --global subword_literals "YYYY-MM-DD" "THH:MM" ":SS"
    set --global subword_descrs
    set --global subword_descr_literal_ids 
    set --global subword_descr_ids 
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[2] "2"
    set --global subword_literal_transitions_tos[2] "3"
    set --global subword_literal_transitions_inputs[3] "3"
    set --global subword_literal_transitions_tos[3] "4"
    set --global subword_command_transitions
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 1 2 3
    set --global subword_literal_inputs_level_1 "1" "2" "3"
    set --global subword_command_froms_level_0 
    set --global subword_commands_level_0 
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_22
    set --global subword_literals "--clusters="
    set --global subword_descrs
    set --global subword_descrs[1] "Comma separated list of clusters to issue"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "7,3"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1
    set --global subword_literal_inputs_level_0 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "7"
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_shape_23
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "1,3"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1
    set --global subword_literal_inputs_level_0 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "1"
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_5
    set --global subword_literals "--input="
    set --global subword_descrs
    set --global subword_descrs[1] "file for batch script's standard input"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_23 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_3
    set --global subword_literals "--error="
    set --global subword_descrs
    set --global subword_descrs[1] "file for batch script's standard error"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_23 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_16
    set --global subword_literals "--container="
    set --global subword_descrs
    set --global subword_descrs[1] "Path to OCI container bundle"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_23 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_6
    set --global subword_literals "--output="
    set --global subword_descrs
    set --global subword_descrs[1] "file for batch script's standard output"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    _sbatch_subword_shape_23 "$argv[1]" "$argv[2]"
end

function _sbatch_subword_54
    set --global subword_literals ","
    set --global subword_descrs
    set --global subword_descr_literal_ids 
    set --global subword_descr_ids 
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[2] "1"
    set --global subword_literal_transitions_tos[2] "1"
    set --global subword_command_transitions
    set --global subword_command_transitions[1] "11,2"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 2
    set --global subword_literal_inputs_level_1 "1"
    set --global subword_command_froms_level_0 1
    set --global subword_commands_level_0 "11"
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_26
    set --global subword_literals "--mail-user="
    set --global subword_descrs
    set --global subword_descrs[1] "who to send email notification for job state changes"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "8,3"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1
    set --global subword_literal_inputs_level_0 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "8"
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_48
    set --global subword_literals ","
    set --global subword_descrs
    set --global subword_descr_literal_ids 
    set --global subword_descr_ids 
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[2] "1"
    set --global subword_literal_transitions_tos[2] "1"
    set --global subword_command_transitions
    set --global subword_command_transitions[1] "13,2"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 2
    set --global subword_literal_inputs_level_1 "1"
    set --global subword_command_froms_level_0 1
    set --global subword_commands_level_0 "13"
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_21
    set --global subword_literals "--licenses=" ","
    set --global subword_descrs
    set --global subword_descrs[1] "required license, comma separated"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[3] "2"
    set --global subword_literal_transitions_tos[3] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "6,3"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1 3
    set --global subword_literal_inputs_level_0 "1" "2"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "6"
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_31
    set --global subword_literals "--partition="
    set --global subword_descrs
    set --global subword_descrs[1] "partition requested"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "9,3"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1
    set --global subword_literal_inputs_level_0 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "9"
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_37
    set --global subword_literals "--cluster-constraint=" "," "!"
    set --global subword_descrs
    set --global subword_descrs[1] "specify a list of cluster constraints"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[2] "3"
    set --global subword_literal_transitions_tos[2] "3"
    set --global subword_literal_transitions_inputs[4] "2"
    set --global subword_literal_transitions_tos[4] "3"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "11,4"
    set --global subword_command_transitions[3] "11,4"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 
    set --global subword_literal_inputs_level_0 
    set --global subword_literal_froms_level_1 1 2 4
    set --global subword_literal_inputs_level_1 "1" "3" "2"
    set --global subword_command_froms_level_0 2 3
    set --global subword_commands_level_0 "11" "11"
    set --global subword_command_froms_level_1 
    set --global subword_commands_level_1 
    set --global subword_max_fallback_level 1
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_10
    set --global subword_literals "--exclusive" "=user"
    set --global subword_descrs
    set --global subword_descrs[1] "allocate nodes in exclusive mode when cpu consumable resource is enabled"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[2] "2"
    set --global subword_literal_transitions_tos[2] "3"
    set --global subword_command_transitions
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1 2
    set --global subword_literal_inputs_level_0 "1" "2"
    set --global subword_command_froms_level_0 
    set --global subword_commands_level_0 
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_9
    set --global subword_literals "--wrap="
    set --global subword_descrs
    set --global subword_descrs[1] "wrap command string in a sh script and submit"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "2,3"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1
    set --global subword_literal_inputs_level_0 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "2"
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_11
    set --global subword_literals "--exclusive" "=mcs"
    set --global subword_descrs
    set --global subword_descrs[1] "allocate nodes in exclusive mode when cpu consumable resource is enabled and mcs plugin is enabled"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[2] "2"
    set --global subword_literal_transitions_tos[2] "3"
    set --global subword_command_transitions
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1 2
    set --global subword_literal_inputs_level_0 "1" "2"
    set --global subword_command_froms_level_0 
    set --global subword_commands_level_0 
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_13
    set --global subword_literals "YYYY-MM-DD" "--begin=" "seconds" "minutes" "THH:MM" "+count" "weeks" "hours" "HH:MM" "days" "now" ":SS"
    set --global subword_descrs
    set --global subword_descrs[1] "defer job until HH:MM MM/DD/YY"
    set --global subword_descr_literal_ids 2
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "2"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[2] "1 9 11"
    set --global subword_literal_transitions_tos[2] "5 4 3"
    set --global subword_literal_transitions_inputs[3] "6"
    set --global subword_literal_transitions_tos[3] "6"
    set --global subword_literal_transitions_inputs[4] "12"
    set --global subword_literal_transitions_tos[4] "7"
    set --global subword_literal_transitions_inputs[5] "5"
    set --global subword_literal_transitions_tos[5] "4"
    set --global subword_literal_transitions_inputs[6] "3 4 7 8 10"
    set --global subword_literal_transitions_tos[6] "7 7 7 7 7"
    set --global subword_command_transitions
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1 2 3 4 5 6
    set --global subword_literal_inputs_level_0 "2" "1 9 11" "6" "12" "5" "3 4 7 8 10"
    set --global subword_command_froms_level_0 
    set --global subword_commands_level_0 
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_2
    set --global subword_literals "--chdir="
    set --global subword_descrs
    set --global subword_descrs[1] "set working directory for batch script"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "1"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_command_transitions
    set --global subword_command_transitions[2] "0,3"
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1
    set --global subword_literal_inputs_level_0 "1"
    set --global subword_command_froms_level_0 2
    set --global subword_commands_level_0 "0"
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function _sbatch_subword_7
    set --global subword_literals "-requeue" "no" "--"
    set --global subword_descrs
    set --global subword_descrs[1] "whether to permit the job to be requeued"
    set --global subword_descr_literal_ids 1
    set --global subword_descr_ids 1
    set --global subword_literal_transitions_inputs
    set --global subword_literal_transitions_inputs[1] "3"
    set --global subword_literal_transitions_tos[1] "2"
    set --global subword_literal_transitions_inputs[2] "1 2"
    set --global subword_literal_transitions_tos[2] "4 3"
    set --global subword_literal_transitions_inputs[3] "1"
    set --global subword_literal_transitions_tos[3] "4"
    set --global subword_command_transitions
    set --global subword_star_transitions_from 
    set --global subword_star_transitions_to 
    set --global subword_literal_froms_level_0 1 2 3
    set --global subword_literal_inputs_level_0 "3" "1 2" "1"
    set --global subword_command_froms_level_0 
    set --global subword_commands_level_0 
    set --global subword_max_fallback_level 0
    _sbatch_subword "$argv[1]" "$argv[2]"
end

function __complgen_match
    set prefix $argv[1]

    set candidates
    set descriptions
    while read c
        set a (string split --max 1 -- "	" $c)
        set --append candidates $a[1]
        if set --query a[2]
            set --append descriptions $a[2]
        else
            set --append descriptions ""
        end
    end

    if test -z "$candidates"
        return 1
    end

    set escaped_prefix (string escape --style=regex -- $prefix)
    set regex "^$escaped_prefix.*"

    set matches_case_sensitive
    set descriptions_case_sensitive
    set i 1
    while test $i -le (count $candidates)
        if string match --regex --quiet --entire -- $regex $candidates[$i]
            set --append matches_case_sensitive $candidates[$i]
            set --append descriptions_case_sensitive $descriptions[$i]
        end
        set i (math $i + 1)
    end

    if set --query matches_case_sensitive[1]
        set i 1
        while test $i -le (count $matches_case_sensitive)
            printf '%s	%s\n' $matches_case_sensitive[$i] $descriptions_case_sensitive[$i]
            set i (math $i + 1)
        end
        return 0
    end

    set matches_case_insensitive
    set descriptions_case_insensitive
    set i 1
    while test $i -le (count $candidates)
        if string match --regex --quiet --ignore-case --entire -- $regex $candidates[$i]
            set --append matches_case_insensitive $candidates[$i]
            set --append descriptions_case_insensitive $descriptions[$i]
        end
        set i (math $i + 1)
    end

    if set --query matches_case_insensitive[1]
        set i 1
        while test $i -le (count $matches_case_insensitive)
            printf '%s	%s\n' $matches_case_insensitive[$i] $descriptions_case_insensitive[$i]
            set i (math $i + 1)
        end
        return 0
    end

    return 1
end

function _sbatch_subword
    set mode $argv[1]
    set word $argv[2]

    set subword_state 1
    set char_index 1
    set matched 0
    while true
        if test $char_index -gt (string length -- "$word")
            set matched 1
            break
        end

        set subword (string sub --start=$char_index -- "$word")

        if set --query subword_literal_transitions_inputs[$subword_state] && test -n $subword_literal_transitions_inputs[$subword_state]
            set inputs (string split ' ' $subword_literal_transitions_inputs[$subword_state])
            set tos (string split ' ' $subword_literal_transitions_tos[$subword_state])

            set stop_matching 0
            set literal_matched 0
            set literal_id 1
            while test $literal_id -le (count $subword_literals)
                set literal $subword_literals[$literal_id]
                if test $subword = $literal
                    set index (contains --index -- "$literal_id" $inputs)
                    set subword_state $tos[$index]
                    set literal_len (string length -- "$literal")
                    set char_index (math $char_index + $literal_len)
                    set literal_matched 1
                    break
                end
                if string match --quiet -- "$subword*" $literal
                    set stop_matching 1
                    break
                end
                if string match --quiet -- "$literal*" $subword
                    set index (contains --index -- "$literal_id" $inputs)
                    set subword_state $tos[$index]
                    set literal_len (string length -- "$literal")
                    set char_index (math $char_index + $literal_len)
                    set literal_matched 1
                    break
                end
                set literal_id (math $literal_id + 1)
            end
            if test $stop_matching -ne 0
                break
            end
            if test $literal_matched -ne 0
                continue
            end
        end
        if set --query subword_command_transitions[$subword_state] && test -n $subword_command_transitions[$subword_state]
            set state_transitions (string split ' ' $subword_command_transitions[$subword_state])
            set command_matched 0
            set matched 0
            for cmd_to in $state_transitions
                set fields (string split ',' $cmd_to)
                set cmd_id $fields[1]
                set to $fields[2]
                set function_name _sbatch_cmd_$cmd_id
                set candidates ($function_name "" "")
                set i 1
                while test $i -le (count $candidates)
                    set candidate_description (string split --max 1 -- "	" $candidates[$i])
                    set candidates[$i] $candidate_description[1]
                    set i (math $i + 1)
                end
                set indexes (
                    set i 1
                    while test $i -le (count $candidates)
                        printf '%s %s %s\n' $i (string length -- $candidates[$i]) $candidates[$i]
                        set i (math $i + 1)
                    end | sort -nrk2,2 -rk3 | string split -f1 ' '
                )
                set decreasing_length (for i in $indexes; echo $candidates[$i]; end)

                for candidate in $decreasing_length
                    if test $candidate = $subword
                        set subword_state $to
                        set match_len (string length -- $candidate)
                        set char_index (math $char_index + $match_len)
                        set command_matched 1
                        break
                    end

                    if string match --quiet -- "$subword*" $candidate
                        set command_matched 1
                        set matched 1
                        break
                    end

                    if string match --quiet -- "$candidate*" $subword
                        set subword_state $to
                        set match_len (string length -- $candidate)
                        set char_index (math $char_index + $match_len)
                        set command_matched 1
                        break
                    end
                end
                if test $command_matched -ne 0
                    break
                end
            end
            if test $matched -ne 0
                break
            end
            if test $command_matched -ne 0
                continue
            end
        end

        set index (contains --index -- "$subword_state" $subword_star_transitions_from)
        if test -n "$index"
            set matched 1
            break
        end

        break
    end

    if test $mode = matches
        return (math 1 - $matched)
    end

    set completed_prefix (string sub --start=$char_index -- $word)

    set matched_prefix
    if test $char_index -eq 1
        set matched_prefix ""
    else
        set matched_prefix (string sub --end=(math $char_index - 1) -- "$word")
    end

    set fallback_level 0
    while test $fallback_level -le $subword_max_fallback_level
        set candidates
        set froms_name subword_literal_froms_level_$fallback_level
        set froms (string split ' ' $$froms_name)
        if contains $subword_state $froms
            set index (contains --index -- "$subword_state" $froms)
            set transitions_name subword_literal_inputs_level_$fallback_level
            set transitions (string split ' ' $$transitions_name[1][$index])
            for literal_id in $transitions
                set completed_prefix_len (string length -- $completed_prefix)
                if test $completed_prefix_len -gt 0
                    set literal $subword_literals[$literal_id]
                    set slice (string sub --end=$completed_prefix_len -- $literal)
                    if test "$slice" != "$completed_prefix"
                        continue
                    end
                end
                set subword_descr_index (contains --index -- "$literal_id" $subword_descr_literal_ids)
                if test -n "$subword_descr_index"
                    set --append candidates (printf '%s%s\t%s\n' $matched_prefix $subword_literals[$literal_id] $subword_descrs[$subword_descr_ids[$subword_descr_index]])
                else
                    set --append candidates (printf '%s%s\n' $matched_prefix $subword_literals[$literal_id])
                end
            end
        end
        set froms_name subword_command_froms_level_$fallback_level
        set froms (string split ' ' $$froms_name)
        set index (contains --index -- "$subword_state" $froms)
        if test -n "$index"
            set subword_commands_level_name subword_commands_level_$fallback_level
            set function_id $$subword_commands_level_name[1][$index]
            set function_name _sbatch_cmd_$function_id
            $function_name "$completed_prefix" "$matched_prefix" | while read line
                set --append candidates (printf '%s%s\n' $matched_prefix $line)
            end
        end
        printf '%s\n' $candidates | __complgen_match && break
        set fallback_level (math $fallback_level + 1)
    end
end


function _sbatch
    set COMP_LINE (commandline --cut-at-cursor)

    set COMP_WORDS
    echo $COMP_LINE | read --tokenize --array COMP_WORDS
    if string match --quiet --regex '.*\s$' $COMP_LINE
        set COMP_CWORD (math (count $COMP_WORDS) + 1)
    else
        set COMP_CWORD (count $COMP_WORDS)
    end

    set literals "--oversubscribe" "--get-user-env" "--spread-job" "--overcommit" "--contiguous" "--parsable" "arbitrary" "--version" "--verbose" "--no-kill" "--usage" "--quiet" "cyclic" "--hold" "--help" "plane" "block" "-x" "-w" "-v" "-t" "-s" "-q" "-p" "-o" "-n" "-m" "-k" "-i" "-h" "-e" "-d" "-c" "-b" "-a" "-W" "-V" "-Q" "-O" "-N" "-M" "-L" "-J" "-H" "-G" "-D" "-C" "-A" "--"
    set descrs
    set descrs[1] "over-subscribe resources with other jobs"
    set descrs[2] "load environment from local cluster"
    set descrs[3] "spread job across as many nodes as possible"
    set descrs[4] "overcommit resources"
    set descrs[5] "demand a contiguous range of nodes"
    set descrs[6] "outputs only the jobid and cluster name (if present), separated by semicolon, only on successful submission."
    set descrs[7] "output version information and exit"
    set descrs[8] "verbose mode (multiple -v's increase verbosity)"
    set descrs[9] "do not kill job on node failure"
    set descrs[10] "display brief usage message"
    set descrs[11] "quiet mode (suppress informational messages)"
    set descrs[12] "submit job in held state"
    set descrs[13] "show this help message"
    set descr_literal_ids 1 2 3 4 5 6 8 9 10 11 12 14 15
    set descr_ids 1 2 3 4 5 6 7 8 9 10 11 12 13
    set literal_transitions_inputs
    set literal_transitions_inputs[1] "1 2 3 4 5 6 8 9 10 11 12 14 15 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49"
    set literal_transitions_tos[1] "2 2 2 2 2 2 2 2 2 2 2 2 2 17 17 2 8 2 15 14 5 3 12 2 5 2 5 9 3 8 3 3 2 2 2 3 11 10 13 2 3 4 16 7 18"
    set literal_transitions_inputs[2] "1 2 3 4 5 6 8 9 10 11 12 14 15 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48"
    set literal_transitions_tos[2] "2 2 2 2 2 2 2 2 2 2 2 2 2 17 17 2 8 2 15 14 5 3 12 2 5 2 5 9 3 8 3 3 2 2 2 3 11 10 13 2 3 4 16 7"
    set literal_transitions_inputs[12] "7 13 16 17"
    set literal_transitions_tos[12] "2 2 2 2"
    set command_transitions
    set command_transitions[1] "1,6"
    set command_transitions[2] "1,6"
    set command_transitions[4] "0,2"
    set command_transitions[5] "1,2"
    set command_transitions[6] "1,19 2,19"
    set command_transitions[7] "3,2"
    set command_transitions[11] "7,2"
    set command_transitions[13] "1,2"
    set command_transitions[14] "9,2"
    set command_transitions[15] "10,2"
    set command_transitions[18] "1,6"
    set command_transitions[19] "1,19 2,19"
    set star_transitions_from 1 13 2 3
    set star_transitions_to 2 2 2 2
    set subword_transitions_ids[1] "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47"
    set subword_transitions_tos[1] "2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2"
    set subword_transitions_ids[2] "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47"
    set subword_transitions_tos[2] "2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2"
    set subword_transitions_ids[8] "50 51 52"
    set subword_transitions_tos[8] "2 2 2"
    set subword_transitions_ids[9] "53"
    set subword_transitions_tos[9] "2"
    set subword_transitions_ids[10] "49"
    set subword_transitions_tos[10] "2"
    set subword_transitions_ids[16] "54"
    set subword_transitions_tos[16] "2"
    set subword_transitions_ids[17] "48"
    set subword_transitions_tos[17] "2"

    set state 1
    set word_index 2
    while test $word_index -lt $COMP_CWORD
        set -- word $COMP_WORDS[$word_index]

        if set --query literal_transitions_inputs[$state] && test -n $literal_transitions_inputs[$state]
            set inputs (string split ' ' $literal_transitions_inputs[$state])
            set tos (string split ' ' $literal_transitions_tos[$state])

            set literal_id (contains --index -- "$word" $literals)
            if test -n "$literal_id"
                set index (contains --index -- "$literal_id" $inputs)
                set state $tos[$index]
                set word_index (math $word_index + 1)
                continue
            end
        end

        if set --query subword_transitions_ids[$state] && test -n $subword_transitions_ids[$state]
            set subword_ids (string split ' ' $subword_transitions_ids[$state])
            set tos (string split ' ' $subword_transitions_tos[$state])

            set subword_matched 0
            for subword_id in $subword_ids
                if _sbatch_subword_$subword_id matches "$word"
                    set subword_matched 1
                    set state $tos[$subword_id]
                    set word_index (math $word_index + 1)
                    break
                end
            end
            if test $subword_matched -ne 0
                continue
            end
        end

        if set --query command_transitions[$state] && test -n $command_transitions[$state]
            set state_transitions (string split ' ' $command_transitions[$state])
            set command_matched 0
            set matched 0
            for cmd_to in $state_transitions
                set fields (string split ',' $cmd_to)
                set cmd_id $fields[1]
                set to $fields[2]
                set function_name _sbatch_cmd_$cmd_id
                set candidates ($function_name "" "")
                set i 1
                while test $i -le (count $candidates)
                    set candidate_description (string split --max 1 -- "	" $candidates[$i])
                    set candidates[$i] $candidate_description[1]
                    set i (math $i + 1)
                end
                set indexes (
                    set i 1
                    while test $i -le (count $candidates)
                        printf '%s %s %s\n' $i (string length -- $candidates[$i]) $candidates[$i]
                        set i (math $i + 1)
                    end | sort -nrk2,2 -rk3 | string split -f1 ' '
                )
                set decreasing_length (for i in $indexes; echo $candidates[$i]; end)

                for candidate in $decreasing_length
                    if test $candidate = $word
                        set state $to
                        set word_index (math $word_index + 1)
                        set command_matched 1
                        break
                    end
                end
                if test $command_matched -ne 0
                    break
                end

                if test (math $word_index + 1) = $COMP_CWORD
                    set command_matched 1
                    set matched 1
                    break
                end
            end
            if test $matched -ne 0
                break
            end
            if test $command_matched -ne 0
                continue
            end
        end

        set index (contains --index -- "$state" $star_transitions_from)
        if test -n "$index"
            set state $star_transitions_to[$index]
            set word_index (math $word_index + 1)
            continue
        end

        return 1
    end

    set literal_froms_level_0 1 2
    set literal_inputs_level_0 "1 2 3 4 6 8 9 10 12 14 15" "1 2 3 4 6 8 9 10 12 14 15"
    set literal_froms_level_1 1 2 12
    set literal_inputs_level_1 "5 11 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49" "5 11 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48" "7 13 16 17"
    set command_froms_level_0 1 2 4 5 6 7 11 13 14 15 18 19
    set commands_level_0 "1" "1" "0" "1" "1 2" "3" "7" "1" "9" "10" "1" "1 2"
    set command_froms_level_1 
    set commands_level_1 
    set --global subword_max_fallback_level 1
    set subword_froms_level_0 1 2
    set subwords_level_0 "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 38 44 45 47" "1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 38 44 45 47"
    set subword_froms_level_1 1 2 8 9 10 16 17
    set subwords_level_1 "37 39 40 41 42 43 46" "37 39 40 41 42 43 46" "50 51 52" "53" "49" "54" "48"

    set fallback_level 0
    while test $fallback_level -le 1
        set candidates
        set froms_name literal_froms_level_$fallback_level
        set froms $$froms_name
        set index (contains --index -- "$state" $froms)
        if test -n "$index"
            set level_inputs_name literal_inputs_level_$fallback_level
            set state_inputs (string split ' ' $$level_inputs_name[1][$index])
            for literal_id in $state_inputs
                set descr_index (contains --index -- "$literal_id" $descr_literal_ids)
                if test -n "$descr_index"
                    set --append candidates (printf '%s\t%s\n' $literals[$literal_id] $descrs[$descr_ids[$descr_index]])
                else
                    set --append candidates (printf '%s\n' $literals[$literal_id])
                end
            end
        end

        set subwords_name subword_froms_level_$fallback_level
        set subwords $$subwords_name
        set index (contains --index -- "$state" $subwords)
        if test -n "$index"
            set subwords_name subwords_level_$fallback_level
            set state_subwords $$subwords_name[1][$index]
            set subwords (string split ' ' $state_subwords)
            for id in $subwords
                set function_name _sbatch_subword_$id
                set --append candidates ($function_name complete "$COMP_WORDS[$COMP_CWORD]")
            end
        end

        set commands_name command_froms_level_$fallback_level
        set commands $$commands_name
        set index (contains --index -- "$state" $commands)
        if test -n "$index"
            set commands_name commands_level_$fallback_level
            set commands (string split ' ' $$commands_name)
            set function_id $commands[$index]
            set function_name _sbatch_cmd_$function_id
            set --append candidates ($function_name "$COMP_WORDS[$COMP_CWORD]" "")
        end

        printf '%s\n' $candidates | __complgen_match $COMP_WORDS[$word_index] && return 0
        set fallback_level (math $fallback_level + 1)
    end
end

complete --erase sbatch
complete --command sbatch --no-files --arguments "(_sbatch)"
