# srun completion script generated by https://github.com/adaszko/complgen v0.10.1-0-g9158856501

if [[ ${BASH_VERSINFO[0]} -lt 4 ]]; then
    echo "This completion script requires bash 4.0 or newer (current is $BASH_VERSION)"
    exit 1
fi

_srun_cmd_0 () {
    sacctmgr show account -nP format=account
}

_srun_cmd_1 () {
    compgen -A file -- "$1"
}

_srun_cmd_2 () {
    squeue -u $USER -ho '%A'
}

_srun_cmd_3 () {
    compgen -A directory -- "$1"
}

_srun_cmd_4 () {
    compgen -c
}

_srun_cmd_5 () {
    sinfo -ho "%G" | sed 's/([^)]*)//g' | tr ':' '\n' | grep -v '^[0-9]' | sort -u
}

_srun_cmd_6 () {
    scontrol show lic
}

_srun_cmd_7 () {
    sacctmgr show cluster -nP format=clusters
}

_srun_cmd_8 () {
    sacctmgr show user -nP format=user
}

_srun_cmd_9 () {
    sinfo -ho %P
}

_srun_cmd_10 () {
    sacctmgr show qos -nP format=name
}

_srun_cmd_11 () {
    sinfo -ho %f
}

_srun_cmd_12 () {
    sacctmgr show reservation -nP format=name
}

_srun_cmd_13 () {
    sinfo -ho %n
}

_srun_subword_60 () {
    local -a literals=("0" ",")
    local -A literal_transitions=()
    literal_transitions[1]="([1]=2)"
    literal_transitions[3]="([0]=1 [1]=2)"
    local -A command_transitions=()
    command_transitions[0]="([6]=1)"
    command_transitions[2]="([6]=3)"
    local -A literal_transitions_level_0=([1]="1" [3]="0 1")
    local -A commands_level_0=([0]="6" [2]="6")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_42 () {
    local -a literals=("--constraint=" ",")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    literal_transitions[2]="([1]=1)"
    local -A command_transitions=()
    command_transitions[1]="([11]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0" [2]="1")
    local -A commands_level_0=([1]="11")
    local -A commands_level_1=()
    local max_fallback_level=1
    _srun_subword "$1" "$2"
}

_srun_subword_54 () {
    local -a literals=(",")
    local -A literal_transitions=()
    literal_transitions[1]="([0]=0)"
    local -A command_transitions=()
    command_transitions[0]="([13]=1)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="0")
    local -A commands_level_0=([0]="13")
    local -A commands_level_1=()
    local max_fallback_level=1
    _srun_subword "$1" "$2"
}

_srun_subword_32 () {
    local -a literals=("--qos=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([10]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="10")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_33 () {
    local -a literals=("--send-libs=" "yes" "no")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    literal_transitions[1]="([1]=2 [2]=2)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([0]="0" [1]="1 2")
    local -A commands_level_0=()
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_58 () {
    local -a literals=("YYYY-MM-DD" "THH:MM" ":SS")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    literal_transitions[1]="([1]=2)"
    literal_transitions[2]="([2]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([0]="0" [1]="1" [2]="2")
    local -A commands_level_0=()
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_15 () {
    local -a literals=("--licenses=" ":0" ",")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    literal_transitions[2]="([2]=3)"
    literal_transitions[4]="([1]=2 [2]=3)"
    local -A command_transitions=()
    command_transitions[1]="([6]=2)"
    command_transitions[3]="([6]=4)"
    local -A literal_transitions_level_0=([0]="0" [2]="2" [4]="1 2")
    local -A commands_level_0=([1]="6" [3]="6")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_0 () {
    local -a literals=("--account=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([0]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="0")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_4 () {
    local -a literals=("--dependency=" "afternotok" "aftercorr" "afterany" "afterok" "after" ":" ",")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    literal_transitions[1]="([1]=2 [2]=2 [3]=2 [4]=2 [5]=2 [7]=1)"
    literal_transitions[2]="([6]=3)"
    literal_transitions[4]="([6]=3 [7]=1)"
    local -A command_transitions=()
    command_transitions[3]="([2]=4)"
    local -A literal_transitions_level_0=([0]="0" [1]="1 2 3 4 5 7" [2]="6" [4]="6 7")
    local -A commands_level_0=([3]="2")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_40 () {
    local -a literals=("--cluster-constraint=" "!")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    literal_transitions[1]="([1]=2)"
    local -A command_transitions=()
    command_transitions[1]="([11]=3)"
    command_transitions[2]="([11]=3)"
    local -A literal_transitions_level_0=([0]="0" [1]="1")
    local -A commands_level_0=([1]="11" [2]="11")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_46 () {
    local -a literals=("--reservation=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([12]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="12")
    local -A commands_level_1=()
    local max_fallback_level=1
    _srun_subword "$1" "$2"
}

_srun_subword_18 () {
    local -a literals=("TIME_LIMIT_90" "TIME_LIMIT_80" "TIME_LIMIT_50" "--mail-type=" "ARRAY_TASKS" "TIME_LIMIT" "STAGE_OUT" "REQUEUE" "BEGIN" "NONE" "FAIL" "END" "ALL")
    local -A literal_transitions=()
    literal_transitions[0]="([3]=1)"
    literal_transitions[1]="([0]=2 [1]=2 [2]=2 [4]=2 [5]=2 [6]=2 [7]=2 [8]=2 [9]=2 [10]=2 [11]=2 [12]=2)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([0]="3" [1]="0 1 2 4 5 6 7 8 9 10 11 12")
    local -A commands_level_0=()
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_34 () {
    local -a literals=("SIGWAITING" "SIGVTALRM" "--signal=" "SIGWINCH" "SIGXFSZ" "SIGXCPU" "SIGUSR2" "SIGUSR1" "SIGTTOU" "SIGTTIN" "SIGTSTP" "SIGTRAP" "SIGTERM" "SIGSTOP" "SIGSEGV" "SIGQUIT" "SIGPROF" "SIGPOLL" "SIGPIPE" "SIGKILL" "SIGCONT" "SIGCHLD" "SIGALRM" "SIGABRT" "SIGURG" "SIGSYS" "SIGPWR" "SIGLWP" "SIGIOT" "SIGINT" "SIGILL" "SIGHUP" "SIGFPE" "SIGEMT" "SIGCLD" "SIGBUS" "SIGAIO" "SIGIO" "R:" "60" "34" "33" "32" "31" "30" "29" "28" "27" "26" "25" "24" "23" "22" "21" "20" "19" "18" "17" "16" "15" "14" "13" "12" "11" "10" "s" "m" "h" "9" "8" "7" "6" "5" "4" "3" "2" "1")
    local -A literal_transitions=()
    literal_transitions[0]="([2]=1)"
    literal_transitions[1]="([0]=3 [1]=3 [3]=3 [4]=3 [5]=3 [6]=3 [7]=3 [8]=3 [9]=3 [10]=3 [11]=3 [12]=3 [13]=3 [14]=3 [15]=3 [16]=3 [17]=3 [18]=3 [19]=3 [20]=3 [21]=3 [22]=3 [23]=3 [24]=3 [25]=3 [26]=3 [27]=3 [28]=3 [29]=3 [30]=3 [31]=3 [32]=3 [33]=3 [34]=3 [35]=3 [36]=3 [37]=3 [38]=2 [40]=3 [41]=3 [42]=3 [43]=3 [44]=3 [45]=3 [46]=3 [47]=3 [48]=3 [49]=3 [50]=3 [51]=3 [52]=3 [53]=3 [54]=3 [55]=3 [56]=3 [57]=3 [58]=3 [59]=3 [60]=3 [61]=3 [62]=3 [63]=3 [64]=3 [68]=3 [69]=3 [70]=3 [71]=3 [72]=3 [73]=3 [74]=3 [75]=3 [76]=3)"
    literal_transitions[2]="([0]=3 [1]=3 [3]=3 [4]=3 [5]=3 [6]=3 [7]=3 [8]=3 [9]=3 [10]=3 [11]=3 [12]=3 [13]=3 [14]=3 [15]=3 [16]=3 [17]=3 [18]=3 [19]=3 [20]=3 [21]=3 [22]=3 [23]=3 [24]=3 [25]=3 [26]=3 [27]=3 [28]=3 [29]=3 [30]=3 [31]=3 [32]=3 [33]=3 [34]=3 [35]=3 [36]=3 [37]=3 [40]=3 [41]=3 [42]=3 [43]=3 [44]=3 [45]=3 [46]=3 [47]=3 [48]=3 [49]=3 [50]=3 [51]=3 [52]=3 [53]=3 [54]=3 [55]=3 [56]=3 [57]=3 [58]=3 [59]=3 [60]=3 [61]=3 [62]=3 [63]=3 [64]=3 [68]=3 [69]=3 [70]=3 [71]=3 [72]=3 [73]=3 [74]=3 [75]=3 [76]=3)"
    literal_transitions[3]="([39]=4)"
    literal_transitions[4]="([65]=5 [66]=5 [67]=5)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([0]="2" [1]="0 1 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 68 69 70 71 72 73 74 75 76" [2]="0 1 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 68 69 70 71 72 73 74 75 76" [3]="39" [4]="65 66 67")
    local -A commands_level_0=()
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_20 () {
    local -a literals=("cray_shasta" "--mpi=" "pmix" "pmi2" "none" "list")
    local -A literal_transitions=()
    literal_transitions[0]="([1]=1)"
    literal_transitions[1]="([0]=2 [2]=2 [3]=2 [4]=2 [5]=2)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([0]="1" [1]="0 2 3 4 5")
    local -A commands_level_0=()
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_26 () {
    local -a literals=("--partition=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([9]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="9")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_shape_15 () {
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    literal_transitions[2]="([1]=1)"
    local -A command_transitions=()
    command_transitions[1]="([13]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0" [2]="1")
    local -A commands_level_0=([1]="13")
    local -A commands_level_1=()
    local max_fallback_level=1
    _srun_subword "$1" "$2"
}

_srun_subword_48 () {
    local -a literals=("--nodelist=" ",")
    _srun_subword_shape_15 "$1" "$2"
}

_srun_subword_49 () {
    local -a literals=("--exclude=" ",")
    _srun_subword_shape_15 "$1" "$2"
}

_srun_subword_19 () {
    local -a literals=("--mail-user=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([8]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="8")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_shape_17 () {
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([4]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="4")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_36 () {
    local -a literals=("--task-prolog=")
    _srun_subword_shape_17 "$1" "$2"
}

_srun_subword_35 () {
    local -a literals=("--task-epilog=")
    _srun_subword_shape_17 "$1" "$2"
}

_srun_subword_55 () {
    local -a literals=("afternotok" "aftercorr" "afterany" "afterok" "after" ":" ",")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1 [1]=1 [2]=1 [3]=1 [4]=1 [6]=0)"
    literal_transitions[1]="([5]=2)"
    literal_transitions[3]="([5]=2 [6]=0)"
    local -A command_transitions=()
    command_transitions[2]="([2]=3)"
    local -A literal_transitions_level_0=([0]="0 1 2 3 4 6" [1]="5" [3]="5 6")
    local -A commands_level_0=([2]="2")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_10 () {
    local -a literals=("--gres=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([5]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="5")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_41 () {
    local -a literals=(",")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([11]=2)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0")
    local -A commands_level_0=([1]="11")
    local -A commands_level_1=()
    local max_fallback_level=1
    _srun_subword "$1" "$2"
}

_srun_subword_6 () {
    local -a literals=("--chdir=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([3]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="3")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_8 () {
    local -a literals=("--export=" ",ENVVAR" "NONE" "ALL")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    literal_transitions[1]="([2]=3 [3]=2)"
    literal_transitions[2]="([1]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([0]="0" [1]="2 3" [2]="1")
    local -A commands_level_0=()
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_shape_23 () {
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    literal_transitions[1]="([1]=2)"
    local -A command_transitions=()
    command_transitions[1]="([4]=2)"
    local -A literal_transitions_level_0=([0]="0" [1]="1")
    local -A commands_level_0=([1]="4")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_28 () {
    local -a literals=("--prolog=" "none")
    _srun_subword_shape_23 "$1" "$2"
}

_srun_subword_9 () {
    local -a literals=("--epilog=" "none")
    _srun_subword_shape_23 "$1" "$2"
}

_srun_subword_shape_24 () {
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    literal_transitions[1]="([1]=2)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([0]="0" [1]="1")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    _srun_subword "$1" "$2"
}

_srun_subword_45 () {
    local -a literals=("--mem-per-gpu=" "64G")
    _srun_subword_shape_24 "$1" "$2"
}

_srun_subword_44 () {
    local -a literals=("--mem-per-cpu=" "8G")
    _srun_subword_shape_24 "$1" "$2"
}

_srun_subword_50 () {
    local -a literals=("--exclusive" "=user")
    _srun_subword_shape_24 "$1" "$2"
}

_srun_subword_47 () {
    local -a literals=("--tmp=" "10G")
    _srun_subword_shape_24 "$1" "$2"
}

_srun_subword_52 () {
    local -a literals=("--cpus-per-gpu=" "8")
    _srun_subword_shape_24 "$1" "$2"
}

_srun_subword_51 () {
    local -a literals=("--exclusive" "=mcs")
    _srun_subword_shape_24 "$1" "$2"
}

_srun_subword_53 () {
    local -a literals=("--gpus=" "1")
    _srun_subword_shape_24 "$1" "$2"
}

_srun_subword_43 () {
    local -a literals=("--mem=" "128G")
    _srun_subword_shape_24 "$1" "$2"
}

_srun_subword_13 () {
    local -a literals=("--jobid=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([2]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="2")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_39 () {
    local -a literals=("--wait=" "0")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    literal_transitions[1]="([1]=2)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([0]="0" [1]="1")
    local -A commands_level_0=()
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_25 () {
    local -a literals=("--output=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([1]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="1")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_shape_28 () {
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    literal_transitions[1]="([1]=2)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([0]="0" [1]="1")
    local -A commands_level_0=()
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_27 () {
    local -a literals=("--priority=" "0")
    _srun_subword_shape_28 "$1" "$2"
}

_srun_subword_30 () {
    local -a literals=("--propagate" "=rlimits")
    _srun_subword_shape_28 "$1" "$2"
}

_srun_subword_2 () {
    local -a literals=("--cpus-per-task=" "8")
    _srun_subword_shape_28 "$1" "$2"
}

_srun_subword_12 () {
    local -a literals=("--immediate" "=1")
    _srun_subword_shape_28 "$1" "$2"
}

_srun_subword_14 () {
    local -a literals=("--job-name=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([1]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="1")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_shape_30 () {
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    literal_transitions[1]="([1]=2)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([0]="0" [1]="1")
    local -A commands_level_0=()
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_24 () {
    local -a literals=("--nodes=" "1")
    _srun_subword_shape_30 "$1" "$2"
}

_srun_subword_31 () {
    local -a literals=("--pty" "=fd")
    _srun_subword_shape_30 "$1" "$2"
}

_srun_subword_11 () {
    local -a literals=("--input=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([1]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="1")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_shape_32 () {
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    literal_transitions[1]="([1]=2)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([0]="0" [1]="1")
    local -A commands_level_0=()
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_21 () {
    local -a literals=("--ntasks=" "1")
    _srun_subword_shape_32 "$1" "$2"
}

_srun_subword_22 () {
    local -a literals=("--nice" "=0")
    _srun_subword_shape_32 "$1" "$2"
}

_srun_subword_shape_33 () {
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([1]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="1")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_3 () {
    local -a literals=("--container=")
    _srun_subword_shape_33 "$1" "$2"
}

_srun_subword_7 () {
    local -a literals=("--error=")
    _srun_subword_shape_33 "$1" "$2"
}

_srun_subword_shape_34 () {
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    literal_transitions[1]="([1]=2)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([0]="0" [1]="1")
    local -A commands_level_0=()
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_57 () {
    local -a literals=("HH:MM" ":SS")
    _srun_subword_shape_34 "$1" "$2"
}

_srun_subword_23 () {
    local -a literals=("--ntasks-per-node=" "1")
    _srun_subword_shape_34 "$1" "$2"
}

_srun_subword_56 () {
    local -a literals=("seconds" "minutes" "weeks" "hours" "days" "now" "+1")
    local -A literal_transitions=()
    literal_transitions[0]="([5]=1)"
    literal_transitions[1]="([6]=2)"
    literal_transitions[2]="([0]=3 [1]=3 [2]=3 [3]=3 [4]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([0]="5" [1]="6" [2]="0 1 2 3 4")
    local -A commands_level_0=()
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_shape_36 () {
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    literal_transitions[1]="([1]=5 [2]=4 [6]=4 [9]=3 [11]=2)"
    literal_transitions[2]="([13]=6)"
    literal_transitions[3]="([12]=4)"
    literal_transitions[5]="([5]=3)"
    literal_transitions[6]="([3]=4 [4]=4 [7]=4 [8]=4 [10]=4)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([0]="0" [1]="1 2 6 9 11" [2]="13" [3]="12" [5]="5" [6]="3 4 7 8 10")
    local -A commands_level_0=()
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_5 () {
    local -a literals=("--deadline=" "YYYY-MM-DD" "MM/DD/YY" "seconds" "minutes" "THH:MM" "MMDDYY" "weeks" "hours" "HH:MM" "days" "now" ":SS" "+1")
    _srun_subword_shape_36 "$1" "$2"
}

_srun_subword_38 () {
    local -a literals=("--time-min=" "YYYY-MM-DD" "MM/DD/YY" "seconds" "minutes" "THH:MM" "MMDDYY" "weeks" "hours" "HH:MM" "days" "now" ":SS" "+1")
    _srun_subword_shape_36 "$1" "$2"
}

_srun_subword_17 () {
    local -a literals=("--distribution=" "arbitrary" "cyclic" "plane" "block")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    literal_transitions[1]="([1]=2 [2]=2 [3]=2 [4]=2)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([0]="0" [1]="1 2 3 4")
    local -A commands_level_0=()
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_59 () {
    local -a literals=(",")
    local -A literal_transitions=()
    literal_transitions[1]="([0]=0)"
    local -A command_transitions=()
    command_transitions[0]="([11]=1)"
    local -A literal_transitions_level_0=()
    local -A literal_transitions_level_1=([1]="0")
    local -A commands_level_0=([0]="11")
    local -A commands_level_1=()
    local max_fallback_level=1
    _srun_subword "$1" "$2"
}

_srun_subword_16 () {
    local -a literals=("--clusters=")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=1)"
    local -A command_transitions=()
    command_transitions[1]="([7]=2)"
    local -A literal_transitions_level_0=([0]="0")
    local -A commands_level_0=([1]="7")
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_1 () {
    local -a literals=("YYYY-MM-DD" "MM/DD/YY" "--begin=" "seconds" "minutes" "THH:MM" "MMDDYY" "weeks" "hours" "HH:MM" "days" "now" ":SS" "+1")
    local -A literal_transitions=()
    literal_transitions[0]="([2]=1)"
    literal_transitions[1]="([0]=5 [1]=4 [6]=4 [9]=3 [11]=2)"
    literal_transitions[2]="([13]=6)"
    literal_transitions[3]="([12]=4)"
    literal_transitions[5]="([5]=3)"
    literal_transitions[6]="([3]=4 [4]=4 [7]=4 [8]=4 [10]=4)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([0]="2" [1]="0 1 6 9 11" [2]="13" [3]="12" [5]="5" [6]="3 4 7 8 10")
    local -A commands_level_0=()
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword_29 () {
    local -a literals=("filesystem" "--profile=" "network" "energy" "task" "none" "all" ",")
    local -A literal_transitions=()
    literal_transitions[0]="([1]=1)"
    literal_transitions[1]="([0]=2 [2]=2 [3]=2 [4]=2 [5]=2 [6]=2 [7]=3)"
    literal_transitions[3]="([0]=4 [2]=4 [3]=4 [4]=4)"
    literal_transitions[4]="([7]=3)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([0]="1" [1]="0 2 3 4 5 6")
    local -A literal_transitions_level_1=([1]="7" [3]="0 2 3 4" [4]="7")
    local -A commands_level_0=()
    local -A commands_level_1=()
    local max_fallback_level=1
    _srun_subword "$1" "$2"
}

_srun_subword_37 () {
    local -a literals=("YYYY-MM-DD" "MM/DD/YY" "seconds" "minutes" "--time=" "THH:MM" "MMDDYY" "weeks" "hours" "HH:MM" "days" "now" ":SS" "+1")
    local -A literal_transitions=()
    literal_transitions[0]="([4]=1)"
    literal_transitions[1]="([0]=5 [1]=4 [6]=4 [9]=3 [11]=2)"
    literal_transitions[2]="([13]=6)"
    literal_transitions[3]="([12]=4)"
    literal_transitions[5]="([5]=3)"
    literal_transitions[6]="([2]=4 [3]=4 [7]=4 [8]=4 [10]=4)"
    local -A command_transitions=()
    local -A literal_transitions_level_0=([0]="4" [1]="0 1 6 9 11" [2]="13" [3]="12" [5]="5" [6]="2 3 7 8 10")
    local -A commands_level_0=()
    local max_fallback_level=0
    _srun_subword "$1" "$2"
}

_srun_subword () {
    [[ $# -ne 2 ]] && return 1
    local mode=$1
    local word=$2

    local subword_state=0
    local char_index=0
    local matched=0
    local nliterals=${#literals[@]}
    while true; do
        if [[ $char_index -ge ${#word} ]]; then
            matched=1
            break
        fi

        local subword=${word:$char_index}

        if [[ -v "literal_transitions[$subword_state]" ]]; then
            local -A state_transitions=${literal_transitions[$subword_state]}

            for ((literal_id = 0; literal_id < nliterals; literal_id++)); do
                local literal=${literals[$literal_id]}
                if [[ $subword == $literal && -v "state_transitions[$literal_id]" ]]; then
                    subword_state=${state_transitions[$literal_id]}
                    char_index=$((char_index + ${#literal}))
                    continue 2
                fi
                if [[ $literal == $subword* ]]; then
                    break 2
                fi
                if [[ $subword == $literal* && -v "state_transitions[$literal_id]" ]]; then
                    subword_state=${state_transitions[$literal_id]}
                    char_index=$((char_index + ${#literal}))
                    continue 2
                fi
            done
        fi

        if [[ -v "command_transitions[$subword_state]" ]]; then
            local matched_prefix="${word:0:$char_index}"
            local -A state_commands=${command_transitions[$subword_state]}
            for cmd_id in "${!state_commands[@]}"; do
                readarray -t subword_candidates < <(_srun_cmd_$cmd_id "$subword" "$matched_prefix" | while read -r f1 _; do echo "$f1"; done)
                if [[ ${#subword_candidates[@]} -gt 0 ]]; then
                    indexes=($(
                        for i in "${!subword_candidates[@]}"; do
                            printf '%s %s %s\n' $i "${#subword_candidates[i]}" "${subword_candidates[i]}"
                        done | sort -nrk2,2 -rk3 | cut -f1 -d' '
                    ))
                    decreasing_length=()
                    for i in "${indexes[@]}" ; do
                        decreasing_length+=("${subword_candidates[i]}")
                    done

                    for candidate in "${decreasing_length[@]}"; do
                        if [[ $candidate == $subword ]]; then
                            match_len=${#candidate}
                            char_index=$((char_index + match_len))
                            subword_state=${state_commands[$cmd_id]}
                            continue 3
                        fi

                        if [[ $candidate == $subword* ]]; then
                            break 3
                        fi

                        if [[ $subword == $candidate* ]]; then
                            match_len=${#candidate}
                            char_index=$((char_index + match_len))
                            subword_state=${state_commands[$cmd_id]}
                            continue 3
                        fi
                    done
                fi
            done
        fi

        break
    done

    if [[ $mode = matches ]]; then
        return $((1 - matched))
    fi

    local matched_prefix="${word:0:$char_index}"
    local completed_prefix="${word:$char_index}"

    local -a subword_candidates=()
    local -a subword_matches=()
    for (( subword_fallback_level=0; subword_fallback_level <= max_fallback_level; subword_fallback_level++ )) {
        eval "local literal_transitions_name=literal_transitions_level_${subword_fallback_level}"
        eval "local -a transitions=(\${$literal_transitions_name[$subword_state]})"
        for literal_id in "${transitions[@]}"; do
            local literal=${literals[$literal_id]}
            subword_candidates+=("$matched_prefix$literal")
        done
        __complgen_match "$matched_prefix$completed_prefix" subword_candidates subword_matches

        eval "local commands_name=commands_level_${subword_fallback_level}"
        eval "local -a transitions=(\${$commands_name[$subword_state]})"
        for command_id in "${transitions[@]}"; do
            readarray -t subword_candidates < <(_srun_cmd_$command_id "$completed_prefix" "$matched_prefix" | while read -r f1 _; do echo "$f1"; done)
            local -a filtered_candidates=()
            __complgen_match "$completed_prefix" subword_candidates filtered_candidates
            for item in "${filtered_candidates[@]}"; do
                subword_matches+=("$matched_prefix$item")
            done
        done

        if [[ ${#subword_matches[@]} -gt 0 ]]; then
            matches+=("${subword_matches[@]}")
            break
        fi
    }
    return 0
}

_srun () {
    if [[ $(type -t _get_comp_words_by_ref) != function ]]; then
        echo _get_comp_words_by_ref: function not defined.  Make sure the bash-completion system package is installed
        return 1
    fi

    local words cword
    _get_comp_words_by_ref -n "$COMP_WORDBREAKS" words cword

    local -a literals=("--quit-on-interrupt" "--kill-on-bad-exit" "--disable-status" "--oversubscribe" "--container-id=" "--preserve-env" "--unbuffered" "--spread-job" "--overcommit" "--contiguous" "YYYY-MM-DD" "--comment=" "arbitrary" "--version" "--verbose" "--no-kill" "MM/DD/YY" "--usage" "--quiet" "--label" "cyclic" "MMDDYY" "--hold" "--help" "plane" "block" "-x" "-w" "-v" "-u" "-t" "-s" "-q" "-p" "-o" "-n" "-m" "-l" "-k" "-i" "-h" "-e" "-d" "-c" "-b" "-X" "-W" "-V" "-Q" "-O" "-N" "-M" "-L" "-K" "-J" "-I" "-H" "-G" "-E" "-D" "-C" "-A" "--" "8" "1" "0")
    local -A literal_transitions=()
    literal_transitions[0]="([0]=2 [1]=2 [2]=2 [3]=2 [4]=2 [5]=2 [6]=2 [7]=2 [8]=2 [9]=2 [11]=2 [13]=2 [14]=2 [15]=2 [17]=2 [18]=2 [19]=2 [22]=2 [23]=2 [26]=17 [27]=17 [28]=2 [29]=2 [30]=3 [31]=2 [32]=14 [33]=13 [34]=7 [35]=8 [36]=12 [37]=2 [38]=2 [39]=7 [40]=2 [41]=7 [42]=5 [43]=4 [44]=3 [45]=2 [46]=15 [47]=2 [48]=2 [49]=2 [50]=8 [51]=11 [52]=10 [53]=2 [54]=9 [55]=8 [56]=2 [57]=18 [58]=2 [59]=6 [60]=16 [61]=1 [62]=19)"
    literal_transitions[2]="([0]=2 [1]=2 [2]=2 [3]=2 [4]=2 [5]=2 [6]=2 [7]=2 [8]=2 [9]=2 [11]=2 [13]=2 [14]=2 [15]=2 [17]=2 [18]=2 [19]=2 [22]=2 [23]=2 [26]=17 [27]=17 [28]=2 [29]=2 [30]=3 [31]=2 [32]=14 [33]=13 [34]=7 [35]=8 [36]=12 [37]=2 [38]=2 [39]=7 [40]=2 [41]=7 [42]=5 [43]=4 [44]=3 [45]=2 [46]=15 [47]=2 [48]=2 [49]=2 [50]=8 [51]=11 [52]=10 [53]=2 [54]=9 [55]=8 [56]=2 [57]=18 [58]=2 [59]=6 [60]=16 [61]=1)"
    literal_transitions[3]="([10]=2 [16]=2 [21]=2)"
    literal_transitions[4]="([0]=2 [1]=2 [2]=2 [3]=2 [4]=2 [5]=2 [6]=2 [7]=2 [8]=2 [9]=2 [11]=2 [13]=2 [14]=2 [15]=2 [17]=2 [18]=2 [19]=2 [22]=2 [23]=2 [26]=17 [27]=17 [28]=2 [29]=2 [30]=3 [31]=2 [32]=14 [33]=13 [34]=7 [35]=8 [36]=12 [37]=2 [38]=2 [39]=7 [40]=2 [41]=7 [42]=5 [43]=4 [44]=3 [45]=2 [46]=15 [47]=2 [48]=2 [49]=2 [50]=8 [51]=11 [52]=10 [53]=2 [54]=9 [55]=8 [56]=2 [57]=18 [58]=2 [59]=6 [60]=16 [61]=1 [63]=2)"
    literal_transitions[8]="([0]=2 [1]=2 [2]=2 [3]=2 [4]=2 [5]=2 [6]=2 [7]=2 [8]=2 [9]=2 [11]=2 [13]=2 [14]=2 [15]=2 [17]=2 [18]=2 [19]=2 [22]=2 [23]=2 [26]=17 [27]=17 [28]=2 [29]=2 [30]=3 [31]=2 [32]=14 [33]=13 [34]=7 [35]=8 [36]=12 [37]=2 [38]=2 [39]=7 [40]=2 [41]=7 [42]=5 [43]=4 [44]=3 [45]=2 [46]=15 [47]=2 [48]=2 [49]=2 [50]=8 [51]=11 [52]=10 [53]=2 [54]=9 [55]=8 [56]=2 [57]=18 [58]=2 [59]=6 [60]=16 [61]=1 [64]=2)"
    literal_transitions[9]="([0]=2 [1]=2 [2]=2 [3]=2 [4]=2 [5]=2 [6]=2 [7]=2 [8]=2 [9]=2 [11]=2 [13]=2 [14]=2 [15]=2 [17]=2 [18]=2 [19]=2 [22]=2 [23]=2 [26]=17 [27]=17 [28]=2 [29]=2 [30]=3 [31]=2 [32]=14 [33]=13 [34]=7 [35]=8 [36]=12 [37]=2 [38]=2 [39]=7 [40]=2 [41]=7 [42]=5 [43]=4 [44]=3 [45]=2 [46]=15 [47]=2 [48]=2 [49]=2 [50]=8 [51]=11 [52]=10 [53]=2 [54]=9 [55]=8 [56]=2 [57]=18 [58]=2 [59]=6 [60]=16 [61]=1)"
    literal_transitions[12]="([12]=2 [20]=2 [24]=2 [25]=2)"
    literal_transitions[15]="([0]=2 [1]=2 [2]=2 [3]=2 [4]=2 [5]=2 [6]=2 [7]=2 [8]=2 [9]=2 [11]=2 [13]=2 [14]=2 [15]=2 [17]=2 [18]=2 [19]=2 [22]=2 [23]=2 [26]=17 [27]=17 [28]=2 [29]=2 [30]=3 [31]=2 [32]=14 [33]=13 [34]=7 [35]=8 [36]=12 [37]=2 [38]=2 [39]=7 [40]=2 [41]=7 [42]=5 [43]=4 [44]=3 [45]=2 [46]=15 [47]=2 [48]=2 [49]=2 [50]=8 [51]=11 [52]=10 [53]=2 [54]=9 [55]=8 [56]=2 [57]=18 [58]=2 [59]=6 [60]=16 [61]=1 [65]=2)"
    literal_transitions[18]="([0]=2 [1]=2 [2]=2 [3]=2 [4]=2 [5]=2 [6]=2 [7]=2 [8]=2 [9]=2 [11]=2 [13]=2 [14]=2 [15]=2 [17]=2 [18]=2 [19]=2 [22]=2 [23]=2 [26]=17 [27]=17 [28]=2 [29]=2 [30]=3 [31]=2 [32]=14 [33]=13 [34]=7 [35]=8 [36]=12 [37]=2 [38]=2 [39]=7 [40]=2 [41]=7 [42]=5 [43]=4 [44]=3 [45]=2 [46]=15 [47]=2 [48]=2 [49]=2 [50]=8 [51]=11 [52]=10 [53]=2 [54]=9 [55]=8 [56]=2 [57]=18 [58]=2 [59]=6 [60]=16 [61]=1 [64]=2)"
    local -A command_transitions=()
    command_transitions[0]="([4]=20)"
    command_transitions[1]="([0]=2)"
    command_transitions[2]="([4]=20)"
    command_transitions[4]="([4]=20)"
    command_transitions[6]="([3]=2)"
    command_transitions[7]="([1]=2)"
    command_transitions[8]="([4]=20)"
    command_transitions[9]="([1]=2 [4]=20)"
    command_transitions[11]="([7]=2)"
    command_transitions[13]="([9]=2)"
    command_transitions[14]="([10]=2)"
    command_transitions[15]="([4]=20)"
    command_transitions[18]="([4]=20)"
    command_transitions[19]="([4]=20)"
    command_transitions[20]="([1]=20)"
    local -A subword_transitions
    subword_transitions[0]="([0]=2 [1]=2 [2]=2 [3]=2 [4]=2 [5]=2 [6]=2 [7]=2 [8]=2 [9]=2 [10]=2 [11]=2 [12]=2 [13]=2 [14]=2 [15]=2 [16]=2 [17]=2 [18]=2 [19]=2 [20]=2 [21]=2 [22]=2 [23]=2 [24]=2 [25]=2 [26]=2 [27]=2 [28]=2 [29]=2 [30]=2 [31]=2 [32]=2 [33]=2 [34]=2 [35]=2 [36]=2 [37]=2 [38]=2 [39]=2 [40]=2 [41]=2 [42]=2 [43]=2 [44]=2 [45]=2 [46]=2 [47]=2 [48]=2 [49]=2 [50]=2 [51]=2 [52]=2 [53]=2)"
    subword_transitions[2]="([0]=2 [1]=2 [2]=2 [3]=2 [4]=2 [5]=2 [6]=2 [7]=2 [8]=2 [9]=2 [10]=2 [11]=2 [12]=2 [13]=2 [14]=2 [15]=2 [16]=2 [17]=2 [18]=2 [19]=2 [20]=2 [21]=2 [22]=2 [23]=2 [24]=2 [25]=2 [26]=2 [27]=2 [28]=2 [29]=2 [30]=2 [31]=2 [32]=2 [33]=2 [34]=2 [35]=2 [36]=2 [37]=2 [38]=2 [39]=2 [40]=2 [41]=2 [42]=2 [43]=2 [44]=2 [45]=2 [46]=2 [47]=2 [48]=2 [49]=2 [50]=2 [51]=2 [52]=2 [53]=2)"
    subword_transitions[3]="([56]=2 [57]=2 [58]=2)"
    subword_transitions[4]="([0]=2 [1]=2 [2]=2 [3]=2 [4]=2 [5]=2 [6]=2 [7]=2 [8]=2 [9]=2 [10]=2 [11]=2 [12]=2 [13]=2 [14]=2 [15]=2 [16]=2 [17]=2 [18]=2 [19]=2 [20]=2 [21]=2 [22]=2 [23]=2 [24]=2 [25]=2 [26]=2 [27]=2 [28]=2 [29]=2 [30]=2 [31]=2 [32]=2 [33]=2 [34]=2 [35]=2 [36]=2 [37]=2 [38]=2 [39]=2 [40]=2 [41]=2 [42]=2 [43]=2 [44]=2 [45]=2 [46]=2 [47]=2 [48]=2 [49]=2 [50]=2 [51]=2 [52]=2 [53]=2)"
    subword_transitions[5]="([55]=2)"
    subword_transitions[8]="([0]=2 [1]=2 [2]=2 [3]=2 [4]=2 [5]=2 [6]=2 [7]=2 [8]=2 [9]=2 [10]=2 [11]=2 [12]=2 [13]=2 [14]=2 [15]=2 [16]=2 [17]=2 [18]=2 [19]=2 [20]=2 [21]=2 [22]=2 [23]=2 [24]=2 [25]=2 [26]=2 [27]=2 [28]=2 [29]=2 [30]=2 [31]=2 [32]=2 [33]=2 [34]=2 [35]=2 [36]=2 [37]=2 [38]=2 [39]=2 [40]=2 [41]=2 [42]=2 [43]=2 [44]=2 [45]=2 [46]=2 [47]=2 [48]=2 [49]=2 [50]=2 [51]=2 [52]=2 [53]=2)"
    subword_transitions[9]="([0]=2 [1]=2 [2]=2 [3]=2 [4]=2 [5]=2 [6]=2 [7]=2 [8]=2 [9]=2 [10]=2 [11]=2 [12]=2 [13]=2 [14]=2 [15]=2 [16]=2 [17]=2 [18]=2 [19]=2 [20]=2 [21]=2 [22]=2 [23]=2 [24]=2 [25]=2 [26]=2 [27]=2 [28]=2 [29]=2 [30]=2 [31]=2 [32]=2 [33]=2 [34]=2 [35]=2 [36]=2 [37]=2 [38]=2 [39]=2 [40]=2 [41]=2 [42]=2 [43]=2 [44]=2 [45]=2 [46]=2 [47]=2 [48]=2 [49]=2 [50]=2 [51]=2 [52]=2 [53]=2)"
    subword_transitions[10]="([60]=2)"
    subword_transitions[15]="([0]=2 [1]=2 [2]=2 [3]=2 [4]=2 [5]=2 [6]=2 [7]=2 [8]=2 [9]=2 [10]=2 [11]=2 [12]=2 [13]=2 [14]=2 [15]=2 [16]=2 [17]=2 [18]=2 [19]=2 [20]=2 [21]=2 [22]=2 [23]=2 [24]=2 [25]=2 [26]=2 [27]=2 [28]=2 [29]=2 [30]=2 [31]=2 [32]=2 [33]=2 [34]=2 [35]=2 [36]=2 [37]=2 [38]=2 [39]=2 [40]=2 [41]=2 [42]=2 [43]=2 [44]=2 [45]=2 [46]=2 [47]=2 [48]=2 [49]=2 [50]=2 [51]=2 [52]=2 [53]=2)"
    subword_transitions[16]="([59]=2)"
    subword_transitions[17]="([54]=2)"
    subword_transitions[18]="([0]=2 [1]=2 [2]=2 [3]=2 [4]=2 [5]=2 [6]=2 [7]=2 [8]=2 [9]=2 [10]=2 [11]=2 [12]=2 [13]=2 [14]=2 [15]=2 [16]=2 [17]=2 [18]=2 [19]=2 [20]=2 [21]=2 [22]=2 [23]=2 [24]=2 [25]=2 [26]=2 [27]=2 [28]=2 [29]=2 [30]=2 [31]=2 [32]=2 [33]=2 [34]=2 [35]=2 [36]=2 [37]=2 [38]=2 [39]=2 [40]=2 [41]=2 [42]=2 [43]=2 [44]=2 [45]=2 [46]=2 [47]=2 [48]=2 [49]=2 [50]=2 [51]=2 [52]=2 [53]=2)"

    local state=0
    local word_index=1
    local nliterals=${#literals[@]}
    while [[ $word_index -lt $cword ]]; do
        local word=${words[$word_index]}

        if [[ -v "literal_transitions[$state]" ]]; then
            local -A state_transitions=${literal_transitions[$state]}

            for ((literal_id = 0; literal_id < nliterals; literal_id++)); do
                if [[ ${literals[$literal_id]} = "$word" ]]; then
                    if [[ -v "state_transitions[$literal_id]" ]]; then
                        state=${state_transitions[$literal_id]}
                        word_index=$((word_index + 1))
                        continue 2
                    fi
                fi
            done
        fi

        if [[ -v "subword_transitions[$state]" ]]; then
            local -A state_transitions=${subword_transitions[$state]}

            for subword_id in "${!state_transitions[@]}"; do
                if _srun_subword_"${subword_id}" matches "$word"; then
                    state=${state_transitions[$subword_id]}
                    word_index=$((word_index + 1))
                    continue 2
                fi
            done
        fi

        if [[ -v "command_transitions[$state]" ]]; then
            local -A state_commands=${command_transitions[$state]}
            for cmd_id in "${!state_commands[@]}"; do
                readarray -t candidates < <(_srun_cmd_$cmd_id "" "" | while read -r f1 _; do echo "$f1"; done)
                if [[ ${#candidates[@]} -gt 0 ]]; then
                    indexes=($(
                        for i in "${!candidates[@]}" ; do
                            printf '%s %s %s\n' $i "${#candidates[i]}" "${candidates[i]}"
                        done | sort -nrk2,2 -rk3 | cut -f1 -d' '
                    ))
                    decreasing_length=()
                    for i in "${indexes[@]}"; do
                        decreasing_length+=("${candidates[i]}")
                    done

                    for candidate in "${decreasing_length[@]}"; do
                        if [[ $candidate == $word ]]; then
                            state=${state_commands[$cmd_id]}
                            word_index=$((word_index + 1))
                            continue 3
                        fi
                    done

                    if [[ $(($word_index + 1)) == $cword ]]; then
                        break 3
                    fi
                fi
            done
        fi

        return 1
    done

    local -A literal_transitions_level_0=([0]="0 1 2 3 4 5 6 7 8 11 14 15 18 19 22 28 29 30 31 32 33 34 35 36 37 38 39 41 42 43 44 45 46 48 49 50 51 52 53 54 55 56 58 59 61" [2]="0 1 2 3 4 5 6 7 8 11 14 15 18 19 22 28 29 30 31 32 33 34 35 36 37 38 39 41 42 43 44 45 46 48 49 50 51 52 53 54 55 56 58 59 61" [3]="10 16 21" [4]="0 1 2 3 4 5 6 7 8 11 14 15 18 19 22 28 29 30 31 32 33 34 35 36 37 38 39 41 42 43 44 45 46 48 49 50 51 52 53 54 55 56 58 59 61 63" [8]="0 1 2 3 4 5 6 7 8 11 14 15 18 19 22 28 29 30 31 32 33 34 35 36 37 38 39 41 42 43 44 45 46 48 49 50 51 52 53 54 55 56 58 59 61 64" [9]="0 1 2 3 4 5 6 7 8 11 14 15 18 19 22 28 29 30 31 32 33 34 35 36 37 38 39 41 42 43 44 45 46 48 49 50 51 52 53 54 55 56 58 59 61" [12]="12 20 24 25" [15]="0 1 2 3 4 5 6 7 8 11 14 15 18 19 22 28 29 30 31 32 33 34 35 36 37 38 39 41 42 43 44 45 46 48 49 50 51 52 53 54 55 56 58 59 61 65" [18]="0 1 2 3 4 5 6 7 8 11 14 15 18 19 22 28 29 30 31 32 33 34 35 36 37 38 39 41 42 43 44 45 46 48 49 50 51 52 53 54 55 56 58 59 61")
    local -A literal_transitions_level_1=([0]="9 13 17 23 26 27 40 47 57 60 62" [2]="9 13 17 23 26 27 40 47 57 60" [4]="9 13 17 23 26 27 40 47 57 60" [8]="9 13 17 23 26 27 40 47 57 60" [9]="9 13 17 23 26 27 40 47 57 60" [15]="9 13 17 23 26 27 40 47 57 60" [18]="9 13 17 23 26 27 40 47 57 60 64")
    local -A commands_level_0=([0]="4" [1]="0" [2]="4" [4]="4" [6]="3" [7]="1" [8]="4" [9]="1 4" [11]="7" [13]="9" [14]="10" [15]="4" [18]="4" [19]="4" [20]="1")
    local -A commands_level_1=()
    local max_fallback_level=1
    local -A subword_transitions_level_0=([0]="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40" [2]="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40" [3]="56 57 58" [4]="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40" [5]="55" [8]="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40" [9]="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40" [10]="60" [15]="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40" [18]="0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40")
    local -A subword_transitions_level_1=([0]="41 42 43 44 45 46 47 48 49 50 51 52 53" [2]="41 42 43 44 45 46 47 48 49 50 51 52 53" [4]="41 42 43 44 45 46 47 48 49 50 51 52 53" [8]="41 42 43 44 45 46 47 48 49 50 51 52 53" [9]="41 42 43 44 45 46 47 48 49 50 51 52 53" [15]="41 42 43 44 45 46 47 48 49 50 51 52 53" [16]="59" [17]="54" [18]="41 42 43 44 45 46 47 48 49 50 51 52 53")

    local ignore_case=$(bind -v | while read -r _ var value; do [[ $var = completion-ignore-case ]] && echo $value; done)
    if [[ $ignore_case = on ]]; then
        __complgen_match () {
            [[ $# -lt 3 ]] && return 1
            local prefix=$1
            declare -n candidates_=$2
            declare -n matches_=$3
            if [[ -z $prefix ]]; then
                matches_+=("${candidates_[@]}")
            else
                prefix=${prefix,,}
                prefix=$(printf '%q' "$prefix")
                for line in "${candidates_[@]}"; do
                    [[ ${line,,} = ${prefix}* ]] && matches_+=("$line")
                done
            fi
        }
    else
        __complgen_match () {
            [[ $# -lt 3 ]] && return 1
            local prefix=$1
            declare -n candidates_=$2
            declare -n matches_=$3
            if [[ -z $prefix ]]; then
                matches_+=("${candidates_[@]}")
            else
                prefix=$(printf '%q' "$prefix")
                for line in "${candidates_[@]}"; do
                    [[ $line = ${prefix}* ]] && matches_+=("$line")
                done
            fi
        }
    fi


    local -a candidates=()
    local -a matches=()
    local max_fallback_level=1
    local prefix="${words[$cword]}"
    for (( fallback_level=0; fallback_level <= max_fallback_level; fallback_level++ )) {
        eval "local literal_transitions_name=literal_transitions_level_${fallback_level}"
        eval "local -a transitions=(\${$literal_transitions_name[$state]})"
        for literal_id in "${transitions[@]}"; do
            local literal="${literals[$literal_id]}"
            candidates+=("$literal ")
        done
        if [[ ${#candidates[@]} -gt 0 ]]; then
            __complgen_match "$prefix" candidates matches
        fi
        eval "local subword_transitions_name=subword_transitions_level_${fallback_level}"
        eval "local -a transitions=(\${$subword_transitions_name[$state]})"
        for subword_id in "${transitions[@]}"; do
            _srun_subword_$subword_id complete "$prefix"
        done
        eval "local commands_name=commands_level_${fallback_level}"
        eval "local -a transitions=(\${$commands_name[$state]})"
        for command_id in "${transitions[@]}"; do
            readarray -t candidates < <(_srun_cmd_$command_id "$prefix" "" | while read -r f1 _; do echo "$f1"; done)
            if [[ ${#candidates[@]} -gt 0 ]]; then
                __complgen_match "$prefix" candidates matches
            fi
        done
        if [[ ${#matches[@]} -gt 0 ]]; then
            local shortest_suffix="$prefix"
            for ((i=0; i < ${#COMP_WORDBREAKS}; i++)); do
                local char="${COMP_WORDBREAKS:$i:1}"
                local candidate=${prefix##*$char}
                if [[ ${#candidate} -lt ${#shortest_suffix} ]]; then
                    shortest_suffix=$candidate
                fi
            done
            local superfluous_prefix=""
            if [[ "$shortest_suffix" != "$prefix" ]]; then
                local superfluous_prefix=${prefix%$shortest_suffix}
            fi
            COMPREPLY=("${matches[@]#$superfluous_prefix}")
            break
        fi
    }

    return 0
}

complete -o nospace -F _srun srun
